### ISSUE TITLE
Zend_Http_Exception: Invalid header line detected

### ISSUE THREAD

**Issue by collymore** [StudioForty9/Recaptcha#51]
Zend_Http_Exception: Invalid header line detected in lib/Zend/Http/Response.php:572
Stack trace:
#0 lib/Zend/Http/Response.php(696): Zend_Http_Response::extractHeaders('HTTP/2 200 \r\nco...')
#1 lib/Zend/Http/Client.php(1110): Zend_Http_Response::fromString('HTTP/2 200 \r\nco...')
#2 lib/Varien/Http/Client.php(61): Zend_Http_Client->request('GET')

I've logged out the full response and can't see an obvious issue with the headers

2018-11-14T17:29:05+00:00 DEBUG (7): HTTP/2 200 
content-type: application/json; charset=utf-8
content-encoding: gzip
date: Wed, 14 Nov 2018 17:29:05 GMT
expires: Wed, 14 Nov 2018 17:29:05 GMT
cache-control: private, max-age=0
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
content-length: 107
server: GSE
alt-svc: quic=":443"; ma=2592000; v="44,43,39,35"

«æRPP*.MNN-.V²R()*MÕ   %g$æä¤æ¥§ÆÄ

MB                                             -t
  Í­,¬M¢À*3òKòsSAªÊËËõrRóó
Ksôós¸j÷à\<Ía
^X^C

This has been working for over a year without issue until today or last few days. 

Is this something you've seen?

Tahnks

**Comment by jasuten** [comment]
It looks like the issue comes from the fact the response is HTTP/2 instead of HTTP/1.1 and the Zend library doesn't support that format. I've modified the checks in the lib/Zend/Http/Response.php file for now but it doesn't feel like a great fix.
